---
- hosts: all
  remote_user: root
  roles:
    - geerlingguy.repo-epel
    - { role: tecris.maven, maven_major: 3, maven_version: 3.5.4, maven_home_parent_directory: /opt, become: yes }
    - opencit
