- name: Download Monit to opencit-external-artifacts
  become: yes
  get_url:
    url: https://mmonit.com/monit/dist/monit-5.5.tar.gz
    dest: /root/opencit-external-artifacts/monit/monit-5.5-linux-src.tgz
    checksum: sha256:8276b060b3f0e6453c9748d421dec044ddae09d3e4c4666e13472aab294d7c53

- name: Download Tomcat to opencit-external-artifacts
  become: yes
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.34/bin/apache-tomcat-7.0.34.tar.gz
    dest: /root/opencit-external-artifacts/apache-tomcat/apache-tomcat-7.0.34.tar.gz
    checksum: md5:0f50494425c24450b4f66dfd4d2aecca

- name: Download vijava to opencit-external-artifacts
  become: yes
  unarchive:
    src: https://sourceforge.net/projects/vijava/files/vijava/VI%20Java%20API%205.5%20Beta/vijava55b20130927.zip
    dest: /root/opencit-external-artifacts/vijava
    remote_src: yes

- name: Move vijava55b20130927.jar to vijava-5.5.jar
  become: yes
  command: mv /root/opencit-external-artifacts/vijava/vijava55b20130927.jar /root/opencit-external-artifacts/vijava/vijava-5.5.jar

- name: Download kmip4j to opencit-external-artifacts
  become: yes
  unarchive:
    src: https://sourceforge.net/projects/kmip4j/files/KMIP4J-V1.0/kmip4j-bin-1.0.zip
    dest: /root/opencit-external-artifacts/kmip4j
    remote_src: yes

- name: Move kmip4j.jar kmip4j-1.0.jar
  become: yes
  command: mv /root/opencit-external-artifacts/kmip4j/jar/kmip4j.jar /root/opencit-external-artifacts/kmip4j/kmip4j-1.0.jar

- name: Download ext2fsd to opencit-external-artifacts
  become: yes
  get_url:
    url: https://sourceforge.net/projects/ext2fsd/files/Ext2fsd/0.62/Ext2Fsd-0.62.exe
    dest: /root/opencit-external-artifacts/ext2fsd/Ext2Fsd-0.62.exe

- name: Download TPM Tools to opencit-external-artifacts
  become: yes
  get_url:
    url: https://sourceforge.net/projects/trousers/files/tpm-tools/1.3.8/tpm-tools-1.3.8.tar.gz
    dest: /root/opencit-external-artifacts/tpm-tools/tpm-tools-1.3.8.tar.gz

- name: Download Java SE Runtime Environment 8u181 to opencit-external-artifacts
  become: yes
  get_url:
    url: "{{ jre_url }}"
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    dest: /root/opencit-external-artifacts/jre-windows/jre-1.8-windows-x64.tar.gz

- name: Clean up old zip files
  become: yes
  command: rm -rf /root/opencit-external-artifacts/*.zip

- name: Clean up old tar files
  become: yes
  command: rm -rf /root/opencit-external-artifacts/*.tar

- name: Clean up XenServer-SDK
  become: yes
  command: rm -rf /root/opencit-external-artifacts/XenServer-SDK

